version: '3.9'

services:
  server:
    build:
      context: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - todo-rs

  database:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: todo
    ports:
      - 27017:27017
    networks:
      - todo-rs

  admin:
    image: mongo-express:latest
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=database
    ports:
      - 8081:8081
    networks:
      - todo-rs

networks:
  todo-rs: